MrMelbert/MapleStationCode

code/datums/greyscale/json_configs/plushie_lizard.json, code/game/objects/items/plushes.dm, jollystation_modules/README.md, jollystation_modules/code/modules/client/loadout_manager.dm, tgui/packages/tgui/index.js
I fixed this in the past, but at some point between the upstream merge and repo move it was unfixed.
Same fix, also some added sanity so it fail less silently.
=> Loadout fixes lost in the repo move

_maps/RandomRuins/SpaceRuins/jolly_berry.dmm, _maps/RandomRuins/SpaceRuins/jolly_nerva.dmm, config/spaceruinblacklist.txt, jollystation.dme, jollystation_modules/code/datums/ruins/space.dm, jollystation_modules/code/game/area/space_station_13_areas.dm
Adds in two new space ruins, as shown here.
_My god. It's been true all along... Also, there is an omnilathe board. One of a kind._
_An abandoned space outpost. With an atmospherics system, gravity generator, gigabeacon and solar array, it is the perfect location to construct any makeshift space station._
New interesting ruins designed to promote base construction and as a result, player creativity.
:cl:
add: Two new space ruins have drifted into the sector around Indecipheres. Information about them is unknown.
/:cl:
=> Adds in the Berry Physics and NERVA Outpost space ruins.

jollystation.dme, jollystation_modules/code/modules/mining/mining_redemption.dm
This PR adds back in, modularily, the ORM's part upgrades causing it to get 2x ore and 2x points at the highest part levels.
We're a lowpop server low on miners, and it gives more of an incentive for science to research tier 4 parts i guess.
:cl:
add: The Ore Redemption Machine is now upgradeable again, in order to make it give out double ore and double points.
/:cl:
=> Adds back in the ORM part upgrades.

_merge_driver.bash
- Fixed an issue in which it wanted the provided directories to be files
- comment checking grep now uses extended regular expression instead of hardcoded string
- dme updater now resolve merge conflicts before combining dmes
=> Merge Driver Update

_maps/map_files/LimaStation/LimaStation.dmm, jollystation_modules/code/game/area/space_station_13_areas.dm
- Ecto-ghost whatever machine in robotics
- Fixes some updated types
- Fixes some missing disposals pipes
- Fixes some missing tiles
- Very minor decal work
- Splits atmospherics into three areas instead of two, gives atmospherics a real room to use for its control center instead of the "upper" room that's probably intended for multiz use
=> Minor Lima updates post-merge

code/game/machinery/computer/medical.dm, code/game/machinery/computer/security.dm, code/game/objects/items/devices/PDA/PDA.dm, code/modules/food_and_drinks/drinks/drinks/bottle.dm, code/modules/mob/living/carbon/human/human.dm, jollystation_modules/README.md, jollystation_modules/code/game/objects/unique_examine_items.dm
Every instance of the +540 year increment is updated to the +555 increment now, with a note on it being a non-module change.
The time is now accurate, and we can tell what time we actually are now.
Also the better solution to this would be to change the time increment to a config option, but that's a refactor for /tg/ to do.
=> Updates everything to be correctly +15 years from /tg/ time.

code/modules/client/preferences.dm
No one's ever gonna use it, but if someone does use it, it will likely break things. Might as well prevent random hardcore characters from generating in that event.
=> Somewhat effectively disbles random hardcore

jollystation_modules/code/modules/mob/living/carbon/human/flavor_text.dm
Clients are wild unpredictable creatures. This is more of a bandaid than a fix but whatever.
=> Fixes(sort of) a null client runtime with flavor text

jollystation_modules/code/modules/mob/living/carbon/pain_implements.dm, jollystation_modules/code/modules/mob/living/carbon/pain_reagents.dm
- The painkiller survival pen now heals slightly less pain than it did before, but addicts you 3x slower, which means you can take 4-5 pens before getting addicted now.
- The emergency painkiller pen now heals slightly more pain but addicts you 3x faster. Using 2 emergency painkiller pens will addict you now, as they're intended... for emergencies.
- aspirin / paracetamol / caffeine now has a pain modifier like the other painkillers.
=> Painkillers: Miner pen buff, emergency kit pen perf

code/modules/client/preferences_savefile.dm, code/modules/client/preferences_toggles.dm, jollystation_modules/README.md, jollystation_modules/code/modules/antagonists/_common/advanced_antag.dm, jollystation_modules/code/modules/client/loadout_manager.dm, jollystation_modules/code/modules/client/loadout_outfit_helpers.dm
- Re-adjusts loadout list sanitization to be streamlined / work more efficiently
- Optimize loadout manager ui_data so getflaticon was not called 30 times per second - preview generation is now only done when the UI is updated or interacted with
- Adjusts some other lazylist manipulations
Loadout manager should run WAYYYY faster (like, 30% less time dilation when someone's using it, cause holy fuck)
=> Optimizes loadout icon generation (for less lag)

jollystation_modules/code/modules/uplink/uplink_infiltrator.dm
- All items with pop-limits have had their pop-limit slashed in half or more. Examples include the ebow, powersink, contract kits, sleeping carp, and no-slips.
- Many infiltrator items have had their prices re-adjusted and reduced. Notably, CQC and cybernetic implants.
- Re-arranged uplink flags a bit, mostly no changes there, Functionally identical.
=> Rebalances the infiltrator uplink slightly

jollystation_modules/code/modules/mob/living/carbon/pain_causes.dm
Flight potions now cause pain when you grow wings. The flavor text implies you are in a great deal of pain when in reality you take 20 brute, which is whatever. It's now a bit more accurate now. Numbers can be tweaked of course.
Already winged species receive ~15% total pain, while non-winged species receive ~25% total pain from a flight potion.
=> Flight potion causes pain

jollystation_modules/code/modules/reagents/chemistry/reagents/rim_reagents.dm
- Luciferium needs to be applied via ingestion, gel, or patch to gain its effects.
- Luciferium is 3x less addictive.
- Cleaned up some of the code for consistency.
- Made some of the rim-chems `solid` instead of `liquid`.
=> Luciferium must be ingested, is (relatively) less addictive

_maps/map_files/LimaStation/LimaStation.dmm
why:
microwave no make 🍞
oven make 🍞
what i do:
microwave (no 🍞) -> oven (yes 🍞)
Also fixes the BO locker I guess.
=> critical lima fix

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, jollystation_modules/README.md
Updated the read.me to include the [MDB IGNORE] tag, as well as the GitHub templates, so we can further get away from the carbon copied /TG/ stuff. 
I'll touch the home page some other time because I really don't care and it has useful tools that anyone new to coding can def use.
Requesting @MrMelbert @sqnztb just a "yeah okay this is okay" ordeal.
=> Updates some backend stuff

jollystation_modules/code/modules/client/preferences/species/lizard.dm, tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
- Makes the prefs menu take up the whole window
- Fixes a hairlizard bug (fuckin hairlizards)
=> Makes the pref menu `t a l l` (and fixes a bug I missed)

_maps/map_files/LimaStation/LimaStation.dmm, jollystation_modules/code/__DEFINES/paperwork_defines.dm, jollystation_modules/code/game/machinery/fax_machine.dm, tgui/packages/tgui/interfaces/_FaxMachine.js
- Fixes the fax ui, which broke due to some tgui core changes
- Fixes the fax machine saying span_whatever in world 
- Allows the fax machine to be unwrenched and moved
- Admin papers that fail to send now qdel automatically (didn't matter that much)
- Faxes now start receiving paperwork by default, added a subtype that doesn't receive by default (for the lawyer and hop)
- The source machine should no longer appear in the destination list of itself
- Restoring routing information now uses the define
=> Fax machine fixes and tweaks

jollystation_modules/code/modules/client/preferences/languages.dm
Reading the language preference before all languages were init'd caused it to think you had an invalid language selected which cleared the preference...
=> Fixes languages, again, maybe

jollystation.dme, jollystation_modules/code/modules/events/solar_flare.dm
Re-PR of #106
Adds a random event, titled "Solar Flare" to the game. 
This random event causes multiple "fireballs" to pop up everywhere around a department for the duration of the event. These fireballs are 2-4 radius diamonds of fire that deal moderate damage to mobs on the tile and of course set fire to anything around. 
- The event as uncommon, about as rare as a radiation storm.
- It can only occur once per shift without admin intervention.
- Once triggered, it will randomly begin sometime in the next 45 to 90 seconds.
- Once began, it will last somewhere between 90 and 150 seconds.
- There's a 30% chance the event will tell the crew where the solar flares are occurring. Otherwise, it will be unknown.
- A solar flare will trigger every 4 to 6 seconds.
- When a solar flare triggers, …
=> Re-pr of Solar Flare event

jollystation.dme, jollystation_modules/code/modules/research/techweb/_research.dm, jollystation_modules/code/modules/research/techweb/all_nodes.dm
Instead of completely overwriting code for the research nodes, lets you just add the IDs _you_ added, using a new variable list.
This way instead of _this_ for one single item addition
You have _this_ for one single item addition
Which makes it way easier to see what the actual addition is.
=> Makes small additions to research nodes easier to see

_maps/map_files/PubbyStation/PubbyStation.dmm
This PR fixes a bunch of stuff from the engi improvement, like a injector for the atmos plasma tank, and does improvements to cargo's decals. A bunch of tile decal layer issues are also fixed in this. Departures also has the decals fixed.
Chapel also has grilles in its windows now and has power in the garden.
also map merger shouldnt be drunk this time
=> [MDB IGNORE] Pubby Fixes Post-Engi Improvement [not drunk map merger edition]

.github/CODEOWNERS
Adds @CRITAWAKETS as a maintainer to Pubby.
Also hopefully I fixed all the pathings for the maps, since I was never pinged for Pubby edits.
=> Codeowners Update

_maps/map_files/PubbyStation/PubbyStation.dmm
Pubby is now updated to 2022 /tg/ code standards.
Basically, the wall mounts are in proper places now, and the cryopods are gone.
Also added an anasthetic tank and surgery mask to robotics, because we can also update to 2022 Maple standards aswell. (roboticists literally need these to do any surgery)
=> [MDB IGNORE] Pubby is now updated to 2022 tg code.

jollystation.dme, jollystation_modules/code/modules/mod/mod_theme.dm
Adds armor to all the basic MODsuits. 
They're all ROUGHLY the same as the old versions of the hardsuits, adjusted down slightly to accommodate for all the added utility (and speed) that MODsuits bring. 
Additionally, syndicate MODsuits now have half their armor innate, and half their armor gained from activating their booster.
=> Adds armor to basic MODsuits 

jollystation_modules/code/modules/antagonists/_common/advanced_objective.dm, jollystation_modules/code/modules/antagonists/advanced_cult/advanced_cult.dm, jollystation_modules/code/modules/antagonists/advanced_cult/advanced_cult_team.dm, jollystation_modules/code/modules/antagonists/advanced_cult/blood_cult/blood_cult_theme.dm, tgui/packages/tgui/interfaces/_AdvancedCultPanel.js
- Fixes cultists with conversion disabled not getting roundend text.
- Renamed `no_coversion` to `conversion_allowed` because it was getting confusing. Not sure why I named it that in the first place?
=> Fixes the roundend text for Cultists with conversion disblaed

jollystation.dme, jollystation_modules/code/modules/client/preferences/name_preferences.dm
- Allows users to input numbers for their character names / backup human name preferences. Primarily for those who play (gross) robots.
=> Allows numbers in name / backup name preferences

_maps/map_files/PubbyStation/PubbyStation.dmm
People wanted it, its a thing from 2022 /tg/ code standards, its departmental order consoles. These replace the stupid supply consoles with shiny new freebie-ordery consolies.
Also, a bunch of visual glitches are fixed from improper overlaying, alongside duplicate and missing decals in certain areas. A revamp of some departments is to be due since some map decals were fixed or added in the development of the map.
=> Adds in departmental order consoles to pubby, fixes minor visual bugs.

_maps/map_files/LimaStation/LimaStation.dmm, _maps/shuttles/cargo_lima.dmm
- Removes a duplicate chair in virology
- Fixes the cargo shuttle's missing conveyor ID
Also:
- Adds bodybag item dispensers to multiple areas that don't already have bodybags but make sense to have them (I.e. genetics, virology, the morgue, robotics)
- Replaces a lot of the tables in medbay with glass tables
Glass tables in medbay look cleaner and nicer than normal tables imo.
=> Minor Lima changes

code/datums/quirks/negative.dm
Random prosthetics call `replace_limb` without setting special, which causes pain
(The targeted prosthetic quirks called special properly so that's funny)
=> Fixes the phantom pain from the random prosthetic quirk

code/game/atom_defense.dm, code/game/atoms.dm, code/modules/mob/living/living_defense.dm
Port of https://github.com/tgstation/tgstation/pull/65075
Projectiles now actually respect armor, making combat _work properly._
=> [CRITICAL] Fixes projectiles not respecting armor.

code/modules/mob/living/damage_procs.dm, code/modules/mob/living/living_defense.dm, maplestation_modules/README.md
Non-modular fix, but it's probably going to get ported in some way to /tg/station anyway.
This fixes the stamina damage _effect_ from projectiles ignoring armor, an example being beanbags doing 55 damage through armor.
Tested:
=> [CRITICAL] Stamina damage effect is now run through an armor calculation.

maplestation_modules/code/modules/antagonists/advanced_cult/clock_cult/items/ratvar_hardsuit.dm
So clockwork armor did literally nothing beforehand. It covered no region of the body aside from the head. It also was missing a bunch of flags that should've been there.
The armor's also been changed to be more reasonable for how you obtain it, since the brass structures only cost iron in terms of resources. Therefore, it's better than a sec vest, but worse than the captain's armor. Not really any balance data on this though since the armor didn't do anything beforehand.
=> Fixes clockwork armor doing literally nothing, gives it more reasonable armor.

maplestation.dme, maplestation_modules/code/modules/projectiles/ammunition/ballistic/shotgun.dm, maplestation_modules/code/modules/projectiles/projectile/bullets/shotgun.dm
So, tech shells have been nerfed. Here's the changelog.
Frag-12 no longer has the innate damage and stunning, the explosion already causes a LOT of damage.
Laser Scatter now does 66 damage over it's 6 pellets (11 per pellet) instead of 90 over it's 6 pellets (15 per pellet). This ends up being under 50 when wearing an armor vest!
Meteor slugs are now a true war crime of a projectile, no longer stunning their opponents and knocking them down for shorter times, but causing an incredible amount of pain.
=> Overrides to rebalance techshells, mostly nerfs.

maplestation.dme, maplestation_modules/code/game/objects/items/toys.dm
Allows players to talk through all toys similar to ventriloquist dummies. Such as typing ":r I am leezord" when in the right hand to talk through them.
=> Talk through toys

_maps/map_files/KiloStation/KiloStation.dmm, _maps/map_files/LimaStation/LimaStation.dmm, _maps/map_files/PubbyStation/PubbyStation.dmm
Adds Coroner Offices to Kilostation*, Limastation**, and Pubbystation***
<details>
<Summary> Picture </summary>
</details>
<details>
<Summary> Picture </summary>
</details>
<details>
<Summary> Picture </summary>
</details>
*Shuffled around a ton of Kilostation maintenance, also adds Ranges to the kitchen, proper spawnpoints for modular jobs, and a little bit more of misc mapping
**I gave Lima a Coroner's Office during the big merge but I'm showing it here for posterity. 
***Also fixed a lot of Active Turfs of Pubby, adds Ranges to the kitchen, and some minor misc remapping
=> Coroning Coroners

maplestation.dme, maplestation_modules/code/modules/client/preferences/_preferences.dm, maplestation_modules/code/modules/client/preferences/loadout_preference.dm, maplestation_modules/code/modules/client/preferences/sound_frequency.dm, maplestation_modules/code/modules/mob/living/speech_and_radio_sounds.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/_speech_frequency.tsx
Adds a character pref to modify frequency of speech sounds. 
Players can modify their speech between 0.5x and 2x frequency -
0.5x being twice as slow / twice as deep, and 2x being twice as fast / twice as high pitched. 
This pref has a "test sound" button in the preference menu. Find the perfect one today.
=> Adds a pref to modify frequency of speech sounds

maplestation_modules/code/modules/client/preferences/_preferences.dm, maplestation_modules/code/modules/client/preferences/languages.dm
Slipped by me replacing `usr` with `user`.
=> Fixes language picker

maplestation.dme, maplestation_modules/code/game/objects/items/devices/scanners/autopsy_scanner.dm
Adds a couple of autopsy scanners roundstart to make dissections less of a pain when there isn't a coroner around
Morgue
Robotics
=> Adds autopsy scanners to the morgue and robotics

_maps/map_files/PubbyStation/PubbyStation.dmm
renember the PR that changed the subtile decals? yeah i forgor one on pubby, sorry.
It's in the engineering supplies room north from the engine, currently the bugged version shows up as pure white texturing on only the quarter of a tile
=> fixes broken decal on pubby

maplestation.dme, maplestation_modules/code/__DEFINES/signals.dm, maplestation_modules/code/datums/components/stackable_item.dm, maplestation_modules/code/modules/clothing/glasses/hud_eyepatches.dm
More of a silly proof of concept rather than a super serious idea.
We have HUDpatches, but why even go to that step? Why not just wear the HUD on your good eye?
Lets you wear a one-eyed HUD in addition to an eyepatch by clicking an eyepatch with it. Both appear on your mob sprite.
Looks a little funny.
=> Adds the ability to wear a HUD with an eyepatch

code/modules/surgery/organs/tongue.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/silverscale.dm
I could push this upstream but I'm lazy
Being statue-form puts you in stasis, meaning you won't continue to bleed or scream in pain or collapse or die to viruses or whatever because you're a statue now. Makes sense right? Even the stasis icon is a statue. Come on.
=> Silverscale tongue puts you in stasis

maplestation_modules/story_content/post_overlay/code/post_overlay.dm
Yeah this just makes it so that the post overlay can be varedited by admins to any other sprite as an overlay. Tested it, it works.
I should probably make a genericized version of this at some point for less technically-oriented admins to have fun with.
=> Makes the post overlay vareditable to any overlay.

maplestation_modules/code/modules/mob/living/carbon/human/species_types/silverscale.dm
I forgot that stasis gives `HANDS_BLOCKED`, so going into statue made you drop stuff
Now it keeps your held items in the statue with you for the duration of your stay (and when it spits you back out, you will re-equip them)
=> Small Silverscale Fix

maplestation.dme, maplestation_modules/code/modules/mob/living/silicon/robot/robot_defines.dm
Yeah this PR just adds admin spawn variants of the AI Shell, where they come with a power cell instead of being set to null.
/mob/living/silicon/robot/shell/admin_spawn
Comes with a high-capacity power cell.
/mob/living/silicon/robot/shell/admin_spawn/bluespace
Comes with a bluespace power cell.
I don't really see any reason for these types to exist outside of admin spawning and maybe a malf AI ability though, since we'd still want the crew to assemble any "Shell Ready-2-Eat" kits if they're obtainable anywhere other than robotics.
=> Adds in admin spawn variants of the AI Shell, which come with power cells.

maplestation_modules/code/modules/client/preferences/height.dm
I realize now that small people gained `TRAIT_DWARF` which overrided height, so size preference is no longer compatible with height preference. 
This also fixes small people having table crawling. Sorry but it was never intended.
=> Height is not compatible with size

maplestation_modules/code/datums/pain/pain.dm
- The apply damage signal proc was missing an argument causing them all to be off by one, which was probably very bad because it was taking `blocked` as `wound_bonus`, and `blocked` could be upwards of 100
- Godmode protects against pain
=> Two quick pain fixes

maplestation_modules/code/modules/pixel_shift/code/pixel_shift_keybind.dm
The default bind of Ctrl + B prevents characters from unpixelshifting. This changes it to V so new players won't have this problem.
=> Changes default Keybind to pixelshift without Ctrl

_maps/map_files/PubbyStation/PubbyStation.dmm
Swaps the transit tube stations to be dispensers instead of simple stations
Adds a cargo request console outside cargo so you can actually order things
=> Small puppy tweaks

_maps/shuttles/emergency_tram.dmm, code/__DEFINES/dcs/signals/signals_atom/signals_atom_main.dm, code/controllers/subsystem/atoms.dm, code/datums/proximity_monitor/proximity_monitor.dm, code/game/atoms.dm, code/game/turfs/open/openspace.dm, code/game/turfs/open/space/space.dm, code/modules/industrial_lift/industrial_lift.dm, code/modules/mining/machine_processing.dm, code/modules/recycling/conveyor.dm, code/modules/unit_tests/create_and_destroy.dm, code/modules/unit_tests/focus_only_tests.dm
Cherrypicking a PR to stop https://github.com/MrMelbert/MapleStationCode/actions/runs/6538665886/job/17755526941?pr=355
=> Tramstation random failure cherrypick

maplestation.dme, maplestation_modules/code/game/objects/structures/crate_lockers/closets/secure/medical.dm
- Roboticists now have access to Aneshetia lockers. 
- Medical lockers (those containing a pile of generic medical equipment) now spawn with shock blankets, since I was in the area.
=> Fixes anesthesia locker access, adds shock blankets to generic medical lockers

maplestation.dme, maplestation_modules/code/modules/cargo/packs.dm, maplestation_modules/code/modules/surgery/organs/autosurgeon.dm
- Adds Liver and *LUNG Emergency Autosurgeons to cargo.
- These cost 2000 credits, but of course can be freely ordered with departmental orders. 
- Requires surgery access. 
- Cannot be self-used instantly, like other auto-surgeons. 
- (They CAN be self-used, just not instantly. It requires a do_after as if used on another person.)
- The only accept their corresponding organ types. 
- These autosurgeons only work on mobs with very damaged or otherwise missing organs. 
Replacing the livers and lungs of people who repeatedly drink themselves is fun and all for the medical staff, but after the nth patient on the same round it maybe gets a little old. 
So, if an MD is starting to get impatient, they can pop in an order for one of these to make their life going forward easier. 
Someone comes …
=> Adds liver and lung autosurgeons to cargo

code/game/objects/items/defib.dm, maplestation_modules/code/modules/clothing/suits/labcoat.dm
Compact defibrillators fit on suit storage slot for labcoats and similar medical outerwear (surgical apron, winter coat). 
It also fits on Medical MODsuits, but that one I'm not sure is necessary since the defibrillator MOD exists and is cooler.
=> Compact defibs fit on labcoats and similar medical gear

maplestation.dme, maplestation_modules/code/__DEFINES/signals.dm, maplestation_modules/code/game/area/space_station_13_areas.dm, maplestation_modules/code/modules/events/solar_flare.dm, maplestation_modules/code/modules/jobs/job_types/assistant.dm, maplestation_modules/code/modules/jobs/job_types/captain.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/vampire.dm
Happy Halloween guys, am I late?
- Re-adds Bat Form
- Vampires are not allowed to enter departments that they do not have permission to. 
- They can obtain permission by asking (verbally) to enter. If a member of that department responds allowing it, you may enter as normal (assuming your ID card has valid access, as well).
=> Re-adds vampire bat form, disallows vampires from entering other departments without permission

_maps/map_files/LimaStation/LimaStation.dmm, maplestation_modules/code/game/area/space_station_13_areas.dm
As a soft-preparation for Bitrunners + I just wanted to work on Lima a bit: Lima's cargo department is now larger and vertical.
=> Makes Lima Cargo Vertical 

code/__DEFINES/is_helpers.dm, code/modules/admin/view_variables/debug_variables.dm, code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, maplestation_modules/code/__DEFINES/_module_defines.dm, maplestation_modules/code/modules/client/preferences/height.dm, maplestation_modules/code/modules/client/preferences/loadout_preference.dm, maplestation_modules/code/modules/loadouts/loadout_items/_loadout_datum.dm, maplestation_modules/code/modules/loadouts/loadout_items/loadout_datum_accessory.dm, maplestation_modules/code/modules/loadouts/loadout_ui/loadout_manager.dm, maplestation_modules/code/modules/loadouts/loadout_ui/loadout_outfit_helpers.dm, tgui/packages/tgui/interfaces/_LoadoutManager.tsx
Players can now have up to 5 loadout presets saved per character.
Other changes:
- Optimized height filter in preference menu, making it a lot less laggy for the server
- Other filters now show in the prefs menu, because I re-added keep together to the dummies. 
- Cherry-picks appearances being visible in VV (for debugging)
=> Adds loadout slots / presets (on a per-character basis)

maplestation_modules/code/game/objects/structures/surgery_table.dm, tgui/packages/tgui/interfaces/_OperatingComputer.tsx
Operating consoles now reports patient blood volume and ""Heart rate"". 
We don't have real heart rate, so this number is faked, based on some conditions about the patient. _(One day it will not be faked, though.)_ The primary intent of this is to tell you when their heart is stopped and they require CPR or defibrillator, but it can also show you stuff like "are they in crit" if their heart rate is very high.
=> Adds Blood Volume and ""Heart Rate"" to operating consoles

maplestation.dme, maplestation_modules/code/modules/cargo/packs.dm, maplestation_modules/code/modules/vending/clothesmate.dm
Pretty much all the generic modular loadout-only items are now obtainable ingame.
The exceptions to this being story content (including kimonos for technical reasons) and the chesed jacket, which the author wanted to remain loadout-only.
You can get them all at the clothesmate, aside from the Ornithid Masks, which are a 300 credit crate containing one of every mask type.
=> Makes some loadout-only items obtainable ingame.

maplestation.dme, maplestation_modules/code/__DEFINES/_module_defines.dm, maplestation_modules/code/__DEFINES/signals.dm, maplestation_modules/code/__DEFINES/traits.dm, maplestation_modules/code/datums/mood_events/quirk_mood_events.dm, maplestation_modules/code/datums/mood_events/reagent_mood_events.dm, maplestation_modules/code/datums/quirks/neutral.dm, maplestation_modules/code/modules/clothing/suits/loadout_suits.dm, maplestation_modules/code/modules/clothing/under/loadout_under.dm, maplestation_modules/code/modules/reagents/chemistry/reagents/drink_reagents.dm
**THE BALANCING IN THIS PR IS NOWHERE NEAR FINAL. TESTMERGE BEFORE MERGING IF POSSIBLE.**
This PR adds in the "Caffeinated" quirk, a quirk all about beverages with that tasty, amazing molecule known as 
1,3,7-Trimethylxanthine.
When starting the round, you have a huge negative moodlet and very low sprint energy, this lasts until you take your first sip of a caffeinated beverage, and pretty much immediately after, you won't ever drop that low again.
From there, drinking a modest amount of caffeinated beverage will allow you to feel energetic, and gain more sprint energy than a normal crew member! You will have less energy than a crew member if your caffeine levels drop low though, so make sure to get a refill once in a while.
You also get some moodlets depending on the type of caffeinated …
=> Adds in the caffeinated quirk. More sprint... If you can keep it.

maplestation_modules/code/datums/quirks/neutral.dm
proof of fixing:
Caffeinated now works properly.
There are some things to be said about good coding practices given how this bug came about, but that's a discussion on upstream's end, not ours.
=> Changes one character, fixes the entirety of caffeine.

_maps/RandomRuins/SpaceRuins/allamericandiner.dmm, code/datums/components/jukebox.dm, code/game/machinery/dance_machine.dm, code/modules/mod/modules/modules_maint.dm, html/changelogs/AutoChangeLog-pr-81176.yml, maplestation.dme, tgstation.dme, tgui/packages/tgui/interfaces/Jukebox.tsx
See the TG PR for more information.
=> Jukebox betterment

code/game/objects/items/devices/scanners/health_analyzer.dm, maplestation_modules/code/game/objects/structures/vital_floor_scanner.dm, maplestation_modules/code/game/objects/structures/vital_reader.dm
- Vitals Floor Scanner can be deconstructed
- Vitals Floor Scanner disables the screen instantly on exit
- Vitals Screen shows you chemicals
=> Vitals Scanner Fixes

code/datums/components/infective.dm, maplestation.dme, maplestation_modules/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm, maplestation_modules/code/modules/surgery/organs/liver.dm
Lizardperson Livers can safely consume rats without risk of catching disease. They've adapted to it. Don't think about it too much.
=> Lizard Livers Let You Eat Rat (Safely) 

code/modules/mob/living/carbon/human/human_update_icons.dm, maplestation_modules/code/__DEFINES/signals.dm, maplestation_modules/code/datums/components/stackable_item.dm, maplestation_modules/code/modules/clothing/glasses/hud_eyepatches.dm
- Examining items that are stackable gives you a hint what you may be able to attach. 
- I realized I could use an existing signal rather than add a new one, so I changed it to use it. 
- I let the intrusive thoughts win and rewrote a bit of `build_worn_icon` to be more readable. 
- Minor improvements thanks to the recent merge.
=> QoL / tweaks to stackable item component

maplestation_modules/code/__DEFINES/magic/magic_defines.dm, maplestation_modules/code/modules/magic/mana/sources/leylines/leyline_intensities.dm
Increases base mana recharge.
Leyline strength picked will be average or higher, so will always be at base mana recharge rate or higher.
=> Buffing leylines

maplestation_modules/code/datums/quirks/neutral.dm
While talking code over with someone, I found out this was missing. Oops!
This would be a NO GBP moment on another codebase.
=> Adds in a missing SIGNAL_HANDLER to caffeinated's code.

code/__HELPERS/colors.dm, code/_onclick/hud/fullscreen.dm, code/modules/client/client_colour.dm
This is subject to further tweaks later but it is fine for now. Probably.
=> Client Colo(u)r Tweaks 

maplestation.dme, maplestation_modules/code/datums/components/stackable_item.dm, maplestation_modules/code/modules/clothing/head/wig.dm
Lets you put hats on top of wigs. Largely cosmetic (currently), IE does not give armor, emit light, block face, etc.
=> Allows you to put hats on wigs

maplestation_modules/code/modules/art/statuettes.dm
Gets rid of the warning of defined but unused variable.
=> Removes Unused Ma

code/datums/components/gunpoint.dm
What
- Trying to use your headset radio while at gunpoint will block the attempt and trigger the gunpoint reaction fire. 
- Speaking into handheld radios also fails (with `.r` or `.l`). 
- However you can still speak into nearby intercoms (with `.i`)
- This also doesn't affect radio implant. And genetics antenna. 
- Also, open-micing is completely unaffected. 
Why
- Makes gunpoint a bit more usable for setting up hostage situations. Stop people from immediately saying `; Hey I'm being held at gunpoint by Urist McSyndie`. 
- And if you're holding someone at gunpoint and want them to say something to the station you can just use open mic.
=> Being held at gunpoint stops you from using your headset

code/modules/cargo/coupon.dm
Sets the omen component in cigarette coupons from infinite to one, like it used to be
=> Makes cigarette omens only trigger once

code/__HELPERS/time.dm
This PR fixes round and station time being incredibly broken on any machine that has a timezone that isn't "0".
Non-modular changes that aren't marked ahead, but it's likely upstream is going to either pretty much port this or refactor the code outright.
Also station time doesn't exactly have feature parity with how it's supposed to work, but only really manifests in some slightly different hour offsets. The original way it worked _does not work in 515_, as negative values no longer work in time2text.
=> Fixes round and station time.

code/datums/components/embedded.dm, code/modules/mob/living/carbon/examine.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/projectiles/ammunition/ballistic/shotgun.dm, code/modules/projectiles/ammunition/special/syringe.dm, code/modules/projectiles/projectile/bullets/dart_syringe.dm, code/modules/projectiles/projectile/bullets/dnainjector.dm, code/modules/projectiles/projectile/energy/stun.dm
- Syringe guns now embed their syringe in the target
- Fired syringes are no longer deleted, IE, can be reused and even picked up if you miss
- Range has been reduced from 50 tiles(???) to 15 tiles
- Mech fired syringes get a range boost, though.
- Embedded syringes will slowly inject their contents into a mob over time
- This means someone with quick wits can attempt to remove the syringe _before_ it starts to inject them.
- DNA Injector Syringe Gun functions similarly, embedding an injector and injecting after a delay
- Shotgun Dart and Chem Dart Gun functions similarly, embedding darts and injecting after a delay. 
- These darts are not reusable and delete when removed 
_(pictured: Rapid Syringe Gun)_
The intent behind this is to transform the Syringe gun from a "poke! now i run away …
=> Syringe Gun Rework

maplestation_modules/code/modules/magic/story_spells/convect.dm
This PR just limits convect to have a maximum temperature delta of 50 and a lower temperature bound of -50C with an upper temperature bound of 100C.
Right now you can cool things to 0K, bring them up to theoretically infinite amounts of heat, and drain entire leylines in one cast of a spell. This might be a little too ludicrous. You could theoretically put the entire atmos supply into one canister and then heat it up by 1000K to cause untold mayhem. Or just continually heat the floor, draining the leylines and burning the station.
The spell still kinda stinks though and I'm not a fan of the code so expect a rework some time in the future, to at the very least make it somewhat useful.
=> Convect is now limited in its temperature bounds and heating/cooling per cast.

maplestation_modules/code/modules/jobs/job_types/noble_ambassador.dm
This gives the noble ambassador their survival box and telescopic baton, which was previously missing by accident
oops
=> Gives the noble ambassador their box and baton.

code/controllers/configuration/entries/game_options.dm, code/controllers/subsystem/processing/station.dm, code/datums/station_traits/_station_trait.dm, code/datums/station_traits/negative_traits.dm, code/datums/station_traits/neutral_traits.dm, code/datums/station_traits/positive_traits.dm, config/game_options.txt
Strait trait costs: Good in theory, but fails in practice. 
While in theory this allows for more rare traits to shine by leaving behind some "budget" to purchase more impactful traits along side smaller ones, in practice this means the less impactful traits (already regulated by higher weights) become soft-guaranteed to roll: as they effectively combine their weights into one. 
When you have a budget of `1`, and you roll a trait that costs `0.3`, you are left with `0.7`. Now you can't buy any traits that cost `1`, but we still want to spend the rest of the budget, so we are now guaranteed to buy a bunch of things that cost `0.5` or `0.3`. This sucks in practice. 
So I reverted it. All traits are `1` cost. 
But I didn't revert it to how the system used to be. In the past, it would roll 3 …
=> Reverts station trait costs, adds general budget

code/__DEFINES/living.dm, code/game/objects/items/weaponry.dm, code/modules/mob/living/living.dm, maplestation.dme, maplestation_modules/code/datums/components/limbless_aid.dm
Holding a cane reduces the movespeed penalty for missing limbs by 50%. Per cane, so you can have two canes for 75%. If you want
=> You walk faster with canes on missing limbs

maplestation_modules/code/modules/cargo/packs.dm
- Adds Sansufentanyl (1 count) to cargo, so you can order some without buying a big ass crate
- Fix Psicodine prescription being wrong for 3 years
=> Add Sansufentanyl prescription to Cargo, fix Psicodine prescription (after 3 years)

maplestation_modules/code/modules/client/preferences/spellbook/items/spellbook_item_lumenomancy.dm, maplestation_modules/code/modules/magic/story_spells/flare.dm
Magical flares now randomly stay alight between 5-10 minutes with lesser flares 1-5 minutes. Lesser flares now have a cooldown alongside their cheaper cost.
=> Adjusts spell Flares Lifetime and Lesser Cooldown

maplestation.dme, maplestation_modules/code/modules/projectiles/ammunition/ballistic/shotgun.dm, maplestation_modules/code/modules/projectiles/projectile/bullets/shotgun.dm, maplestation_modules/code/modules/research/designs/autolathe_designs.dm, maplestation_modules/code/modules/research/designs/mecha_designs.dm, maplestation_modules/code/modules/research/designs/medical_designs.dm, maplestation_modules/code/modules/research/designs/wiremod_designs.dm
i just wanna print an ER laser man
Aside from fixing material costs being ~20x higher on non-modular designs, this PR also removes some deadcode intended to nerf the scatter laser. It doesn't work anymore and upstream brought in an even bigger nerf. going from a 2-shot kill here to a 3 shot kill with very punishing fall-off, youch.
=> Converts designs to defines, removes unused scatter laser change.

code/__DEFINES/living.dm, maplestation_modules/code/datums/pain/pain.dm, maplestation_modules/code/datums/pain/pain_bodyparts.dm, maplestation_modules/code/datums/pain/pain_causes/surgery_pain.dm, maplestation_modules/code/datums/pain/pain_helpers.dm, maplestation_modules/code/datums/pain/pain_modifiers.dm, maplestation_modules/code/datums/pain/pain_status_effects/pain_limp.dm, maplestation_modules/code/datums/quirks/negative.dm, maplestation_modules/code/modules/reagents/chemistry/withdrawal/luciferium_addiction.dm
- General pain code cleanup
- Numb quirk now stops the "visible" effects of pain, such as the feedback messages and emotes. 
- It however does not stop most of the "mechanical" effects, such as dropping items. They are simply rethemed. 
-  Luciferium Addiction doesn't process on stasis
=> Numbness stops pain effects (and some other changes)

code/__DEFINES/mobs.dm, code/_onclick/hud/human.dm, code/_onclick/hud/screen_objects.dm, code/datums/elements/footstep.dm, code/datums/keybinding/living.dm, code/datums/quirks/negative_quirks/nyctophobia.dm, code/datums/voice_of_god_command.dm, code/game/machinery/flasher.dm, code/game/objects/effects/decals/remains.dm, code/game/turfs/open/_open.dm, code/modules/admin/smites/ghost_control.dm, code/modules/clothing/glasses/_glasses.dm, code/modules/mob/living/living.dm, code/modules/mob/mob_movement.dm, maplestation.dme, maplestation_modules/code/modules/mob/living/sneak.dm, maplestation_modules/code/modules/mob/living/sprint.dm
Changes
- Walk is the default move mode. 
- Sneak mode 1.5x slower than walk mode. 
- `"Hold to toggle move intent"` hotkey has been repurposed to `"Hold to toggle sprint"`, IE, holding the hotkey will put you on run mode while you hold it
- `"Press to cycle move intent"` hotkey will now cycle in a circle, walk -> run -> sneak -> walk, etc
- `"Hold to toggle sneak" hotkey is a thing which is `"Hold to toggle sprint"` but for sneak, obviously. 
- Clicking on the movement selector on your hud will cycle walk -> run -> sneak -> walk, right clicking will go in reverse walk -> sneak -> run -> walk
Todo
- An `"Inverted press to cycle move intent"` hotkey which cycles backwards
- Sprites. I have no sneak mode sprites and no desire to sprite a sneak mode button for like 12 huds, so I just slapped …
=> Adds sneak mode to replicate the old "no footstep" behavior of walking

code/_onclick/hud/robot.dm, code/modules/mob/living/silicon/robot/robot_movement.dm
I forgot cyborgs exist. 
Now they have a move selector on their hud. 
Sprinting as a borg uses energy per tile sprinted, a very small amount but eventually noticeable without an upgraded cell.
=> Adds borg sprinting

code/modules/surgery/organs/internal/tongue/_tongue.dm, maplestation_modules/code/modules/client/preferences/species/lizard.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/_modular_species_features.tsx
Adds a preference allowing lizards to have (slightly) shorter or (much) longer hisses, to represent different drawls.
=> Lets Lizards Customize Hiss Length

maplestation_modules/code/modules/client/preferences/species/lizard.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/_modular_species_features.tsx
Very simple, lizards can choose which layer to put their horns on between `Default`, `Above Hair`, and `Above Helmet`.
=> Adds preference for lizard horn layer

code/__HELPERS/atoms.dm, code/_onclick/item_attack.dm, code/datums/components/blood_walk.dm, code/datums/components/bloody_spreader.dm, code/datums/components/bloodysoles.dm, code/game/atom/_atom.dm, code/game/objects/effects/decals/cleanable/humans.dm, code/modules/antagonists/changeling/powers/mutations.dm, code/modules/clothing/head/_head.dm, code/modules/forensics/forensics_helpers.dm, code/modules/mob/living/basic/ruin_defender/wizard/wizard.dm, code/modules/mob/living/basic/space_fauna/cat_surgeon.dm, code/modules/mob/living/basic/trooper/abductor.dm, code/modules/mob/living/basic/trooper/trooper.dm, code/modules/mob/living/blood.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/carbon_defense.dm, code/modules/mob/living/carbon/carbon_update_icons.dm, code/modules/mob/living/carbon/human/human_update_icons.dm, code/modules/mob/living/living.dm, code/modules/mob/living/simple_animal/hostile/zombie.dm, code/modules/reagents/reagent_containers/blood_pack.dm, code/modules/surgery/surgery_step.dm, maplestation_modules/code/game/objects/items/weaponry.dm, maplestation_modules/code/modules/mob/living/blood.dm
Basically wearing gloves means you don't take blood DNA at all, so tracking bloody footprints didn't function correctly. This has been fixed. 
In fixing this blood has been made more...sensible. Slightly. 
- Humans will now bloody their hands while doing surgery.
- Your mask and helmet can now get bloody if you're using a weapon with very high force. 
- Bloody spreader items (meat) now only bloodies your hands
- Hugging/grabbing someone while your hands/gloves are bloody will spread the blood
- Uniform accessories may get bloody if your uniform gets bloody
=> Fix wearing gloves causing bloody footprints to glitch out

code/datums/elements/footstep.dm, code/modules/mob/living/carbon/human/_species.dm, code/modules/mob/living/carbon/human/human_movement.dm, code/modules/surgery/bodyparts/parts.dm, code/modules/surgery/bodyparts/species_parts/lizard_bodyparts.dm, maplestation_modules/code/datums/elements/shoe_footstep.dm
Kapu tipped me off on the way to fix diagonal footsteps so I did it here
I took this opportunity to also steal another idea from them, of making Digitigrade footsteps use the claw sounds instead of the human sounds. All my own code though
=> Digi lizards now have claw footsteps, diagonal footstep fix

maplestation_modules/code/modules/mob/living/carbon/human/species_types/synth/synth.dm
- Rad immune
- No longer dismember immune (You can use the funny quirk to pop your limbs off now) 
- Fixes disguise eyes not being visible
- Synth bodyparts are organic when disguised. 
- This means while disguised, all chems work on synths (though they're still immune to chems which harm / heal organs, as their organs remain cybernetic), and you can use sutures/meshes on their parts (as was originally intended)
=> Synth tweaks

_maps/shuttles/emergency_lima.dmm, code/__DEFINES/dcs/signals/signals_mob/signals_mob_living.dm, code/__HELPERS/radiation.dm, code/datums/mood_events/generic_negative_events.dm, code/datums/mutations/hulk.dm, code/game/objects/items/cards_ids.dm, code/game/objects/items/cigs_lighters.dm, code/game/objects/items/hand_items.dm, code/game/objects/structures/crates_lockers/closets/bodybag.dm, code/game/objects/structures/morgue.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/_species.dm, code/modules/mob/living/carbon/human/emote.dm, code/modules/surgery/organs/external/tails.dm, code/modules/unit_tests/tail_wag.dm, maplestation_modules/code/datums/components/knockoff_move.dm, maplestation_modules/code/datums/id_trim/jobs.dm, maplestation_modules/code/game/objects/structures/item_dispensers.dm, maplestation_modules/code/modules/jobs/job_types/_job.dm, maplestation_modules/code/modules/jobs/job_types/asset_protection.dm, maplestation_modules/code/modules/jobs/job_types/bridge_officer.dm, maplestation_modules/code/modules/jobs/job_types/noble_ambassador.dm, maplestation_modules/code/modules/jobs/job_types/ordnance_tech.dm, maplestation_modules/code/modules/jobs/job_types/xenobiologist.dm, maplestation_modules/code/modules/loadouts/loadout_items/loadout_datum_belts.dm, maplestation_modules/code/modules/research/designs/autolathe_designs.dm, maplestation_modules/code/modules/research/techweb/all_nodes.dm, maplestation_modules/story_content/prince_equipment/code/clothing.dm
- Anchored items don't get irradiated. 
- Primarily for stuff like intercoms, it's hard to wash those
- `*swish` emote (*wag, but only for a second.)
- Species which have no tail natively are unable to wag tails they gain through surgery
- Fixes our jobs not showing up correctly on crew monitor
- Fixes id trims for some of our jobs (and edits) not being colored
- This makes the noble ambassador ID look kinda bad, but I don't know if that's because the ID itself is not the correct sprite or just because it looks bad. Revisit later?
- Fixes loadout belts overriding important job equipment (for parameds, primarily) 
- Fixes cig butt visible message
- Clicking on a morgue unit - when the tray is extended - will push the tray back in in situations where you can't reach the unit itself BUT can …
=> Scratches random things off the TODO list

_maps/map_files/PubbyStation/PubbyStation.dmm, _maps/shuttles/escape_pod_large.dmm
Just a small amount of changes and fixes to Pubby to make the map keep being maintained.
Firelocks in sci and cargo have been moved to prevent roundstart toggling from the server room and space dock respectively.
A small lighting pass has been done to the map, fixing up improperly dark spots. This isn't a full lighting pass which would also add in things like dim lights, this just fixes weirdly dark spots in the map. Bitrunning also didn't have a light, which has been fixed.
**The monastery shuttle actually works now.**
=> Pubby changes and fixes.

code/__DEFINES/living.dm, code/_onclick/hud/new_player.dm, code/controllers/subsystem/job.dm, code/controllers/subsystem/ticker.dm, code/modules/client/preferences.dm, code/modules/client/preferences/middleware/jobs.dm, code/modules/client/preferences_savefile.dm, code/modules/mob/dead/dead.dm, code/modules/mob/dead/new_player/logout.dm, code/modules/mob/dead/new_player/new_player.dm, maplestation.dme, maplestation_modules/code/modules/client/preferences/ready_anominity.dm, maplestation_modules/code/modules/jobs/job_types/bridge_officer.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/_ready_anominity.tsx
The status tab in the lobby now prints all the players who are readied up.
**By default** it only shows ckey. Character and Top Job are anonymous.
**There is however** a preference that allows you to toggle visibility of character and top job (or your ckey if you really want). 
The intent behind this is so people can better plan around their roundstart job positions, most notably for jobs like captain or contested jobs like chaplain. 
People often discuss what they're playing before the round so might as well expedite it for those who care.
=> Changes lobby ready up printout

code/datums/status_effects/debuffs/grabbed.dm
Melee cd is not handled in melee, but before melee. Which we skip here.
=> Fix mauling

code/modules/food_and_drinks/machinery/grill.dm
Now accumulates 3.33x slower, and is also capped at how much nutriment is in the food or 5 units, meaning a single grilled object can't overdose you.
=> Tweaks grill char

maplestation_modules/code/datums/components/limbless_aid.dm
Canes no longer count as assisting you while pocketed.
=> Fix canes in pockets

code/datums/components/caltrop.dm, code/datums/components/tackle.dm, code/game/objects/obj_defense.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/projectiles/projectile.dm
1.
If a bullet would fully shatter a window, there's an 80% chance the shot will continue.
2.
Being tossed against a (non-reinforced) window now does considerably more damage (to the window)
By default, normal windows require a human to be chucked at it twice to break.
If the toss would shatter the window, you would instead fly _through_ the window, assuming it has no grille. 
This does additional damage (to you) and may cause the shards to embed.
(Demo, has since been tweaked)
https://github.com/user-attachments/assets/0d6156f0-ecba-4799-9eea-805d8272a197
=> Adds defenestration and bullet penetrating glass

code/datums/status_effects/wound_effects.dm, maplestation_modules/code/datums/components/limbless_aid.dm, maplestation_modules/code/datums/quirks/negative.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/limp.tsx
Very simple quirk. It makes you limp every other step, as if your leg was wounded. Using a cane prevents the limp. 
You can choose which side you want limping, as well as if you spawn with a cane (and what type of cane), and how intense the limp is. 
Important to note, this is a guaranteed* limp every other step, where normally wounds are an RNG chance to limp.
*While under the effects of adrenaline from combat, you have a 25% chance to not limp. I left that in.
=> Adds Limping Quirk

code/__DEFINES/reagents.dm, code/modules/reagents/chemistry/holder/ui_data.dm, code/modules/reagents/chemistry/recipes/medicine.dm, code/modules/reagents/chemistry/recipes/toxins.dm, maplestation_modules/code/datums/pain/pain_implements.dm, maplestation_modules/code/datums/pain/pain_reagents/painkiller_reactions.dm, maplestation_modules/code/datums/pain/pain_reagents/painkiller_related_chems.dm, maplestation_modules/code/modules/cargo/packs.dm, maplestation_modules/code/modules/reagents/chemistry/reagents/rim_reagents.dm, tgui/packages/tgui/interfaces/Reagents.jsx
Getting stuck with in addiction for like 20 minutes for messing around with chems (or accidentally getting someone else stuck with an addiction for like 20 minutes because of a mistake) is lame and boring. So here's some chemicals to help with that. 
- Naloxone (1 part morphine, 1 part hydrogen, 1 part chlorine). Purges opiates (oxycodone, morphine, etc) and helps cure opiate addiction. Causes minor disgust.
- Buproprion (1 part propionic acid, 1 part hydrogen, 1 part chlorine). Very slightly purges stimulants and nicotine and helps cure stimuland and nicotine addiction. Causes minor disgust, also gives you a minor positive moodlet.
Both can be ordered as a cargo prescription. 
Other:
- Adds a tag for pain so you can sort by it. Sorts a few reagent tags. 
- Fix Ondansetron having double …
=> Adds some anti-addiction chemicals, also finally adds a reagent tag for pain for sorting

code/modules/clothing/suits/wintercoats.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/synth/synth.dm
- Synths have a more "comfortable" range of temperatures, from extremely-cold to rather-hot
- EVA Winter Coats no longer hides jumpsuit sprite
=> Expands Synth temp range, EVA coat fix

maplestation_modules/code/modules/language/language_holder.dm
This code adds more languages to the AI. 
I made this so CaLE can understand and speak more languages, it was missing quite a few.
The languages I chose were ones that CaLE would know IC at this current point of time. If adding yangyu is a bit much, tell me and I will remove it.
Languages added:
1. Draconic
2. Yangyu
=> Adds more languages to the AI.

code/modules/mob/living/life.dm
Miners keep dying to extreme colds, and I'm pretty sure it's happening because a shaft miner's outfit provides 95% insulation, meaning getting very cold = you don't heat up unless you take it off
Resolving this involves rewriting insulation which is on the docket but until then we can provide a warning message saying why they so cold
=> Cold damage stopgap until insulation rework

code/game/machinery/doors/door.dm, code/game/machinery/doors/windowdoor.dm, code/modules/mob/living/basic/farm_animals/bee/_bee.dm, code/modules/mob/living/basic/jungle/leaper/leaper.dm, code/modules/mob/living/basic/jungle/mega_arachnid/mega_arachnid.dm, code/modules/mob/living/basic/space_fauna/space_dragon/space_dragon.dm, code/modules/mob/living/carbon/alien/adult/queen.dm, code/modules/mob/living/simple_animal/hostile/alien.dm
Cockroaches, butterflies, chickens, and similarly small mobs can't bump open (public access) airlocks unless they are controlled by a player.
Basically no more butterflies escaping captivity and spreading across the station and no more cockroaches jumpscaring you in maint
I also went through and tweaked some mobsizes which made little sense to me (why are bees large?)
=> Small and tiny mobs cannot bump open doors (when AI controlled)

maplestation.dme, maplestation_modules/code/datums/brain_damage/split_personality.dm
This version of Split Personality, instead of randomly changing, adds a new action shared between the two players which can be turned on or off.
If both of them are on, the players switch control on mutual demand instead.
Don't ask me why.
=> Polite Split Personality (non-random Split Personality Variant)

code/game/atom/atom_examine.dm, code/modules/mob/living/carbon/examine.dm
1. You can examine accessories, as intended
2. You can't examine cybernetic implants
3. Adds pronouns to the examine title of humans
This is something Goon does which I thought was "Yeah sure why not". 
The examine bar for humans has a lot of blank space because they don't have an icon associated, so might as well fill it
=> Examine tweaks + Pronouns in bio

code/__DEFINES/bodyparts.dm
Prosthetics have this modifier on them to make their effective hp equivalent to that of normal limbs, however this results in rather unfun gameplay of literally being crit in two hits
So I'm just tweaking the numbers to be closer to default across the board. This is solved in the medrework so that's what makes it temporary
=> Temporary fix for prothetic users being crit in two hits

code/game/objects/effects/decals/cleanable/humans.dm, maplestation_modules/code/modules/mob/living/blood.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/silverscale.dm
Follow up to blood optimization, this fixes runtimes from Silverscale blood (which is full white, which is `null` color in byond) 
But I need to revisit Silverscale blood anyway because - while it's working As Intended with the new effect - I think it's kinda ugly
=> Silverscale blood runtime fixes and tweaks

code/_globalvars/lists/flavor_misc.dm, code/controllers/subsystem/discord.dm, code/datums/brain_damage/mild.dm, code/game/atoms_movable.dm, code/game/machinery/telecomms/computers/logbrowser.dm, code/game/say.dm, code/modules/language/_language.dm, code/modules/language/_language_holder.dm, code/modules/language/beachbum.dm, code/modules/language/codespeak.dm, code/modules/language/common.dm, code/modules/language/uncommon.dm, maplestation_modules/code/modules/antagonists/advanced_cult/clock_cult/clock_language.dm, maplestation_modules/code/modules/language/highdraconic.dm
Some languages can only partially understand another language, rather than it being a binary thing
For example, if you know Draconic, you can (now) only understand 66% of words spoken by someone in Tiziran Draconic
This percentage change is not flat, though: It scales depending on how common the word is (...in the english dictionary). Words in the top 500 most common words are easier to understand (meaning more likely to translate), while words beyond the top 500 most common words are harder to understand (meaning less likely to translate)
As a bonus: The top 1000 most common words are now static when translated into a new language - while they still random from round to round, they will now be the same through the *entire* round, rather than (occasionally) being re-randomized. This means …
=> Adds partial language understanding

code/_globalvars/lists/flavor_misc.dm, code/_globalvars/lists/mobs.dm, code/controllers/subsystem/discord.dm, code/controllers/subsystem/processing/quirks.dm, code/datums/brain_damage/mild.dm, code/datums/quirks/neutral_quirks/foreigner.dm, code/datums/quirks/positive_quirks/bilingual.dm, code/game/atoms_movable.dm, code/game/machinery/telecomms/computers/logbrowser.dm, code/game/say.dm, code/modules/client/preferences/language.dm, code/modules/client/preferences_savefile.dm, code/modules/language/_language.dm, code/modules/language/_language_holder.dm, code/modules/language/beachbum.dm, code/modules/language/codespeak.dm, code/modules/language/common.dm, code/modules/language/uncommon.dm, code/modules/mob/living/living_say.dm, maplestation_modules/code/datums/quirks/good.dm, maplestation_modules/code/modules/antagonists/advanced_cult/clock_cult/clock_language.dm, maplestation_modules/code/modules/client/preferences/languages.dm, maplestation_modules/code/modules/language/highdraconic.dm, maplestation_modules/code/modules/language/isatoan.dm, maplestation_modules/code/modules/language/japanese.dm, tgui/packages/tgui/interfaces/PreferencesMenu/_LanguagePicker.tsx, tgui/packages/tgui/interfaces/PreferencesMenu/data.ts
Updates the language menu
Deletes Bilingual, Trilingual, and Foreigner quirks (Bilingual may be readded, giving you more language slots?)
Now you can choose to remove languages your species starts with
Now you can choose to only understand or only speak a language, rather than having both
Languages given to you by the preference are tied to the mind
A few languages are no longer blocked behind being a certain species (may return?) 
Now shows you what languages you have partial understanding of (may be its own preference in the future?)
=> Language Menu (like the one in the preferences) Rework

code/datums/world_topic.dm, code/modules/plumbing/plumbers/pill_press.dm
This PR cherry-picks https://github.com/tgstation/tgstation/pull/88367 and https://github.com/tgstation/tgstation/pull/88002
These are high-priority security fixes, so, yeah.
=> Cherry-picks two server security fixes.

code/datums/records/manifest.dm, maplestation_modules/code/datums/quirks/neutral.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/mutation.tsx
Neutral quirk which lets you spawn with a choice of a neutral mutation.
(Chav, Medieval, Nervous, Swedish, Unintelligible, Wacky) 
The mutation is mutadone-proof so you won't lose it randomly by accident.
=> Adds Minorly Mutation quirk

code/modules/jobs/job_types/chaplain/chaplain_nullrod.dm, code/modules/religion/burdened/psyker.dm
The revolver is normally reserved for highly burdened chaplains, but I figured it was such a banger chaplains should be able to select it if they want
It's fairly weak; not being able to crit in a single magazine, so I think this is fine
However I didn't want to leave burdened chaplains in the dust, so now the revolver they get as a reward for their dedication is a buffed version - it *can* crit in a single magazine, among other things. 
I also gave it some minor changes, like "You must be a chaplain to pray for a reload" and "Chaplains can flip it without having a holster"
=> Adds chaplain's revolver to Nullrod selection

maplestation_modules/code/datums/quirks/neutral.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/colorblind.tsx
Example of Deuteranopia:
These are the same colors as used in the colorblindness testing in the debug menu made accessible, and no, Tritanopia is *not* accurate in the slightest.
=> Adds in the colorblind quirk.

code/__DEFINES/MC.dm, code/__DEFINES/subsystems.dm, code/__HELPERS/game.dm, code/controllers/master.dm, code/controllers/subsystem/assets.dm, code/controllers/subsystem/early_assets.dm, code/controllers/subsystem/mapping.dm, code/controllers/subsystem/radioactive_nebula.dm, code/controllers/subsystem/ticker.dm, code/controllers/subsystem/title.dm, code/datums/mapgen/CaveGenerator.dm, code/modules/client/preferences/init_stats.dm, code/modules/mob/dead/new_player/login.dm, maplestation.dme, tgstation.dme, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/init_stats.tsx
Init time is displayed on text that scrolls on the left side of the lobby screen
The text will fade out 30 seconds to roundstart
There is also a preference to hide it entirely, so you can enjoy the lobby art.
=> Moves init time display out of chat (and make it hideable since most people don't care)

code/__DEFINES/MC.dm, code/__DEFINES/subsystems.dm, code/__HELPERS/game.dm, code/controllers/master.dm, code/controllers/subsystem/assets.dm, code/controllers/subsystem/early_assets.dm, code/controllers/subsystem/mapping.dm, code/controllers/subsystem/radioactive_nebula.dm, code/controllers/subsystem/ticker.dm, code/controllers/subsystem/title.dm, code/datums/mapgen/CaveGenerator.dm, code/modules/admin/admin_verbs.dm, code/modules/client/preferences/init_stats.dm, code/modules/mob/dead/new_player/login.dm, code/modules/mob/dead/new_player/new_player.dm, maplestation.dme, maplestation_modules/code/modules/client/verbs/looc.dm, tgstation.dme, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/init_stats.tsx
Or "Why I did #656" 
Rather than needing to use OOC to talk pre-round, there is now a bespoke lobby chat
You talk in it as you would expect: Using the say box/verb (`say "Hey I'm in the lobby"`)
This offers people (me) who disable OOC (or move it to another tab) an easier and more visible way to communicate with people pre-round, without needing to mess with their settings
Additionally, this chat persists after roundstart, so it gives people a way to coordinate prior to late-joining. 
(Admins are relayed messages from this chat while in game, so any pre-latejoin metagaming can be finger-wagged)
Color not final, OOC still exists
=> Adds a bespoke pre-game lobby chat 

maplestation_modules/code/modules/mob/living/carbon/human/species_types/abductor.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/android.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/ethereal.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/felinid.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/flypeople.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/monkey.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/mothmen.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/plasmamen.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/podpeople.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/shadowpeople.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/skeletons.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/skrell.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/species.dm, maplestation_modules/code/modules/mob/living/speech_and_radio_sounds.dm, maplestation_modules/code/modules/surgery/organs/tongue.dm
Yeah, this PR makes the speech sound work on tongues rather than hardcoded getters for every species.
This means you can take out someone's tongue, replace it with another species' tongue and get those speech sounds instead!
Also makes it way more easily vareditable for admins and coder/sound design testing.
=> Speech sounds for carbon mobs work on tongue rather than species.

code/modules/mob/living/carbon/human/species_types/lizardpeople.dm, maplestation_modules/code/modules/client/preferences/species/lizard.dm, maplestation_modules/code/modules/mob/living/carbon/human/species_types/silverscale.dm
Looks cool + makes it a bit easier to explain other than "magic" or something
=> Silverscale Aura now dims in darkness

_maps/RandomRuins/IceRuins/icemoon_underground_mailroom.dmm, _maps/map_files/PubbyStation/PubbyStation.dmm, code/__DEFINES/polls.dm, code/__HELPERS/pronouns.dm, code/controllers/subsystem/polling.dm, code/datums/candidate_poll.dm, code/modules/antagonists/valentines/heartbreaker.dm, code/modules/antagonists/valentines/valentine.dm, code/modules/cargo/goodies.dm, code/modules/events/holiday/vday.dm
Just a port of the event rework
=> Valentines Day

code/modules/clothing/head/jobs.dm, code/modules/clothing/suits/jobs.dm, code/modules/clothing/suits/wintercoats.dm
the new beret colors
In addition, the Captain's Parade Vest (not to be confused with the parade jacket) now has the stats of captain's armor, aswell as the same equipment allowance. It previously didn't even have any armor. This means you can combine drip and protection, how neat! Felt off anyway that the jacket is so flaunty and yet the austere vest is unusable as armor.
The captain's winter coat has also been brought up in armor. The original values seem to have been copied beforehand from security armor and not captain armor, making it have very off armor values compared to everything else the cap has. Now it's using captain's armor values as a base, but slightly lowered to compensate for winter coats having additional effects.
=> Captain's Beret is brought up to the modern captain's palette colors, captain's clothes get a protection lookover.

tgui/packages/tgui/interfaces/CommunicationsConsole/Main.tsx, tgui/packages/tgui/interfaces/CommunicationsConsole/types.ts
the "message mu" option was accidentally removed when TGUI was updated across the board, and also needed updating to work. oops.
this brings it back.
also i checked the other Mu stuff and it seems to work perfectly fine
=> You can message Mu again.

code/modules/mob/inventory.dm, maplestation.dme, maplestation_modules/code/__DEFINES/keybinding.dm, maplestation_modules/code/modules/quick_store/open_close_storage.dm
As it says on the tin, this PR makes it so if you have a storage open and an empty hand, pressing quick equip (E by default) will try to pull items from it, this PR also adds a new hotkey (defaulting to Shift+R) to close open storage, or open storage on your person (in order from held storage items, then the backpack, then the belt, if higher priority slots are empty.)
this PR also makes it so active storage is prioritized over suit storage/pockets when quick equipping something into storage.
also if anyone can think of a better name for the new hotkey than "open/close storage" I'd also appreciate that.
=> Quick equip from active storage, as well as a hotkey to close storage interfaces, and open equipped/held storage items

code/game/objects/structures/holosign.dm
Oops. Maybe it should check for both sneak AND walk, but I figure sneaking is more deliberate, so it's more sensible.
=> Holo bariers check for sneak, not walk

code/game/objects/items/food/martian.dm, code/game/objects/items/food/moth.dm, code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm, html/changelogs/AutoChangeLog-pr-92217.yml, maplestation_modules/code/modules/reagents/chemistry/reagents/drink_reagents.dm
Martian drinks in our version didn't get a 2024 PR that made them not all `DRINK_NICE` quality, so this adds that PR
I also took the liberty of making the starfruit drinks not exclusively `DRINK_GOOD` quality as well
the new tiers are as follows
Unchanged:
-Starfruit Lubricant
-Starfruit Soda
-Space Muse
Very Good:
-Starfruit Latte (same quality as Pumpkin Latte)
-Astral Flame
Fantastic: 
-Forgotten Star
-Starbeam Shake (Requires vanilla as well)
=> [CHERRY-PICK] Buffs Various Drink Qualities

code/modules/reagents/reagent_containers/cups/_cup.dm
When drinking from a glass or open container, your character will take notice on how empty the glass is getting.
RN if you're drinking from a bottle that has no filled sprite, you have no way to tell how much is left outside of examining it. 
I like the flavor of this, but I also thought this could just be integrated into the "drink action" to make it a bit more seamless.
=> Bar RP QOL (drink messages indicate how full the bottle is) 

html/statbrowser.css, html/statbrowser.js, tgui/packages/tgui/backend.ts, tgui/public/tgui.html
Gets rid of the annoying white flash when opening TGUI windows. Most based fix thanks Zewaka
=> TGUI window flashing begone
