- jollystation.dme
- jollystation_modules/code/__DEFINES/examine_defines.dm
- jollystation_modules/code/__DEFINES/spans.dm
- jollystation_modules/code/datums/elements/unique_examine.dm
- jollystation_modules/code/datums/quirks/good.dm
- jollystation_modules/code/modules/antagonists/_common/advanced_antag.dm
- jollystation_modules/code/modules/antagonists/_common/advanced_objective.dm
- jollystation_modules/code/modules/antagonists/advanced_heretic/advanced_heretic.dm
- jollystation_modules/code/modules/antagonists/advanced_heretic/eldritch_knowledge.dm
- jollystation_modules/code/modules/antagonists/advanced_traitor/advanced_traitor.dm
- jollystation_modules/code/modules/antagonists/infiltrator/advanced_infiltrator.dm
- jollystation_modules/code/modules/antagonists/infiltrator/infiltrator.dm
- jollystation_modules/code/modules/client/verbs/looc.dm
- jollystation_modules/code/modules/mob/living/carbon/human/examine.dm
- jollystation_modules/code/modules/mob/living/carbon/human/human_helpers.dm
- jollystation_modules/code/modules/mob/pixel_shift.dm
- jollystation_modules/code/modules/uplink/uplink_devices.dm
- Replaces (almost) all spans used in module files with span macros
- Messes a bit with unique_examine element
- Messes a lot with examine flavor text, still needs a bit of attention / it's currently somewhat hacky, but i'll do that at another time
> Replaces a bunch of spans with span macros, also messes with flavor a bit

- _maps/map_files/LimaStation/LimaStation.dmm
- code/datums/shuttles.dm
- code/modules/vending/megaseed.dm
- jollystation.dme
- jollystation_modules/code/datums/shuttles.dm
- jollystation_modules/code/modules/hydroponics/grown/beans.dm
Lima:
- Bluespace Gas Vendors
- Less Carps
- More decal works
- Maint areas fixed up a bit
- Cryo windoor rotated
- Missing disposals pipe in warehouse
- Dupe buttons in HoP office
- Areas split up more
- More wall mounts messed around with
- Cargo belt works
- EVA has more regular stuff
- Tons of misc changes
And...
- Leemah beans correctly modularized
- Lima shuttles correctly modularized
> More Lima Fixes

- code/modules/clothing/head/misc_special.dm
- code/modules/keybindings/bindings_atom.dm
- code/modules/mob/mob_movement.dm
- Reverts the SSInput changes that caused the weird laggy double movements
- Fixes wigs
> Cherrypicks a few upstream changes

- .github/PULL_REQUEST_TEMPLATE.md
- code/__DEFINES/mobs.dm
- code/game/world.dm
- config/dynamic.json
- config/game_options.txt
- config/lavaruinblacklist.txt
- config/spaceruinblacklist.txt
- jollystation_modules/README.md
Contributing file is updated, so people can stop filling it out (why would you even do it knowing we don't have a CL, yet at least)
Mob move speed has been decreased by 0.5. 
Also for once, Goof wasn't smoking crack, increased min age to 18 and max to 300 (may lower if its a problem).
Stat panel clock is fixed; No more 23:00:00. Comment there shouldn't be touched, or I WILL kill you.
Extended should be brought back. Now people can shut the fuck up about black orbit when Dynamic can't spend anything on anything.
Night shifts are on (didn't know this was a config)
> Tweaks, updates and fixes

- jollystation_modules/code/modules/mob/living/carbon/human/examine.dm
> Fixes an examine runtime

- jollystation_modules/code/modules/mob/living/living.dm
Title. "But shouldn't you address mute people in general to make sure they all work?" Whatever, dude.
> Sign languag-ers no longer make speech sounds

- code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
- jollystation_modules/code/modules/antagonists/advanced_heretic/eldritch_knowledge.dm
- No longer gibs on failed sacrifices. 
- Dead folk being sacrificed no longer gib either, and are revived. If the revive fails, then it disembowels them instead.
- Bugfixes and general grammar checkup.
- Comments.
- Adjusted some of the values to account for pain
> Heretic Sacrifice Post-Pain Touch Up

- .github/CODEOWNERS
- config/config.txt
- interface/interface.dm
- interface/skin.dmf
- jollystation_modules/README.md
This swaps around some of the buttons + adds in our own things;
Modular CL (which links to the doc), our rules (Discord link, must be logged into Discord desktop). Also moves the buttons around and stuff. If we can, we could set up our own CL like /TG/ has.
Housekeeping: Added myself to the config folder as a code owner.
> Changes some of the UI buttons

- _maps/map_files/LimaStation/LimaStation.dmm
> Adds ERP zone to Lima's science department.

- _maps/map_files/PubbyStation/PubbyStation.dmm
Updates Pubby to fit more in line with TG standards, including nuking some var edited items, such as light fixtures. Will take away.
Also using this as a bug fix PR due to map diffs and other conflict bullshit.
> Pubby Standardization 

- jollystation_modules/code/datums/pain.dm
- jollystation_modules/code/datums/quirks/good.dm
- jollystation_modules/code/datums/quirks/negative.dm
- jollystation_modules/code/game/machinery/fax_machine.dm
- jollystation_modules/code/modules/antagonists/_common/advanced_antag.dm
- jollystation_modules/code/modules/antagonists/_common/antag_datum.dm
- jollystation_modules/code/modules/antagonists/advanced_heretic/advanced_heretic.dm
- jollystation_modules/code/modules/library/skill_learning/job_skillchips/mining.dm
- jollystation_modules/code/modules/mob/living/carbon/human/species_types/species.dm
- jollystation_modules/code/modules/mob/living/carbon/pain_bodyparts.dm
- jollystation_modules/code/modules/mob/living/carbon/pain_causes.dm
- jollystation_modules/code/modules/mob/living/carbon/pain_reagents.dm
I knew that recieve is not the correct way to spell receive and yet somehow it's managed to typo into literally everything
> Fixes some misspellings 

- jollystation.dme
- jollystation_modules/code/game/objects/unique_examine_items.dm
- jollystation_modules/code/modules/mob/living/simple_animal/friendly/dog.dm
> King Dufresne

- _maps/map_files/LimaStation/LimaStation.dmm
Re-applies some of the various changes, namely the stuff from #37, to Lima that was lost in the rework.
> Sloppily re-applies some of the undone fixes / changes to Lima pre-multi z

- tools/build/build.js
Makes our build tool build our files again.
> Fix the build tool to build module files again

- jollystation_modules/code/modules/antagonists/_common/advanced_traitor_panel.dm
- tgui/packages/tgui/interfaces/_AdvancedHereticPanel.js
- tgui/packages/tgui/interfaces/_AdvancedTraitorPanel.js
- tgui/packages/tgui/interfaces/_AdvancedTraitorParts.js
- tgui/packages/tgui/interfaces/_PixelShift.js
Advanced Antag Panel was the first TGUI I ever made and it was a bit messy as far as standards goes. Goes through and changes flexes to stacks, enforces line standards, pleases the linter. Also makes it thinner and more streamlined slightly.
Fixes some other bugs with the UI I found while testing that I missed ages ago.
Also, Pixel Shift was missing a section tag the whole time, so I threw it in. Should look slightly better.
> Updates Advanced Antag Panel / Pixel Shift Panel to more modern standards / fresher style

- jollystation.dme
- jollystation_modules/code/game/machinery/cryopod.dm
there's definitely a better way of doing this.
deletes anything that doesn't have the indestructible tag
shouldn't conflict with anything in theory but uhhh y'know.
also makes it so borgs don't drop their mmis
> [modular] makes it so that unimportant items are deleted upon cryoing

- jollystation_modules/code/modules/clothing/spacesuits/hardsuit.dm
`rad` flag was removed from armors and no one told me, removed it from the silly blood-red hardsuit
> Hotfix for CI

- jollystation_modules/code/modules/mob/living/carbon/human/species_types/felinid.dm
no more human sfx on exclamation and ask says.
> The worlds smallest fix: Cats now speak cat

- code/__HELPERS/_string_lists.dm
- code/__HELPERS/files.dm
Cherry picks fixes to strings_replacement to make master not constantly fail.
> Cherry-picks strings fix to make master not fail

- code/__DEFINES/maps.dm
- code/_compile_options.dm
- code/controllers/subsystem/mapping.dm
- code/datums/map_config.dm
- code/modules/admin/verbs/maprotation.dm
Ports another PR to fix broken stuff
> Fix change map

- _maps/map_files/LimaStation/LimaStation.dmm
- Space tile in bar
- I used cold lights for all the lights in the hallway, apparently
- Some window stuff, too
> [MDB IGNORE] Fixes some Lima issues

- jollystation_modules/code/datums/pain/pain.dm
- jollystation_modules/code/modules/mob/living/carbon/pain_bodyparts.dm
Atomized some pain fixes out of #123 . 
- Fixes an issue with the health analyzer signal that happened with /tg/'s signal replaced our signal.
- Fixes a potential issue with stamcritting people in pain.
> Atomized Pain fixes

- _maps/map_files/PubbyStation/PubbyStation.dmm
I did a bunch of changes around the place, but i think the most telling one is this.
That's right, its a supermatter far enough away that the engineering rooms can actually be used.
There are also changes to decals around the place and changes to the HFR room.
Further improvements to engineering will happen at the same time as the science improvements, since there will be major structural changes, so stay tuned.
> Improves pubby engineering in many ways.

- _maps/map_files/PubbyStation/PubbyStation.dmm
I didn't test this but I'm assuming these manifolds in sci maint were what was creating the loop. Hopefully its fixed.
> Fixes Pubby Disposals

- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/_hear_radio_sounds.tsx
- Corrects the name of the `toggle radio` preference.
> Fix radio pref name

- jollystation_modules/code/modules/loadouts/loadout_items/loadout_datum_gloves.dm
I KNEW I put in those gloves somewhere, they were wrong the whole time
> Fixes some glove loadout items 

- jollystation_modules/code/__DEFINES/pain_defines.dm
- jollystation_modules/code/datums/pain/pain.dm
- jollystation_modules/code/modules/library/skill_learning/job_skillchips/mining.dm
- jollystation_modules/code/modules/mob/living/carbon/pain_causes.dm
- jollystation_modules/code/modules/mob/living/carbon/pain_shock.dm
- Refactored miner skillchip to use signals. Neat.
- Removed moan from pain emotes. I thought it'd be fine but it's just weird. 
- Tweaked the occurrences of some pain emotes when taking on pain. 
- Pain now makes you stutter, because I find stuttering very funny. More pain, more stutter. 
- Adjusted some odds for effects of pain, Some things should be less common, some more common.
> Some pain tweaks and refactoring

- jollystation_modules/code/modules/antagonists/advanced_cult/blood_cult/blood_cult_theme.dm
- jollystation_modules/code/modules/antagonists/advanced_cult/clock_cult/items/ratvar_hardsuit.dm
- jollystation_modules/code/modules/antagonists/advanced_cult/conversion_rune.dm
- jollystation_modules/code/modules/antagonists/advanced_cult/magic_invoker.dm
- Fixes a runtime on conversion
- Fixes making spells costing a lot of blood
- Fixes using the wrong span on conversion
> Minor Advanced Cult Fixes

- .vscode/extensions.json
- .vscode/settings.json
Also removes an obsolete plugin for syntax highlighting that's essentially replaced by SpacemanDMM.
This is the DMI editor by AnturK, for clarification.
> Adds in the new DMI editor plugin as a recommended VSCode plugin.

- _maps/map_files/LimaStation/LimaStation.dmm
Makes the bar a little larger, and gives it a cute little hallway bar
Also puts a box of drinking glasses on the table at roundstart, since it was missing one while other maps had it.
with pipes
without pipes
_Yes I noticed that there's a hanging light at the hallway bar, I dealt with that after I took the pics oops_
> [MDB IGNORE] Makes the Lima bar less claustrophobic, and gives it hallway access

- _maps/map_files/LimaStation/LimaStation.dmm
- Weird maintenance hall behind med storage gone. 
- Bug ice pops gone.
> Fixes really dumb things I left in Lima

- _maps/map_files/LimaStation/LimaStation.dmm
Adds another door from the main medical area so you don't need to drag someone through the hall to get to the operating room
Hopefully this makes people actually use it more 💀
> Greatly enhances the surgical abilities of Limastation

- _maps/map_files/LimaStation/LimaStation.dmm
Tin
It didn't have a computer before so we couldn't print art.
As for the second entrance, it felt really cramped without it.
(I moved the plant after the screenshot)
> Adds a computer console & second entrance to Lima's library

- _maps/map_files/KiloStation/KiloStation.dmm
Stakes our claim on Kilostation
- Replaces the showroom flooring in Medbay and Sci with white flooring
- Minor remaps to medbay
- Removes the third(!?) surgery room that leads into virology,
- Moves the Cargo Consoles out of the middle of the hallway
- Moves the fax machine out of the middle of the hallway
- Wall mount nudging
- Adds unique lockers to council room 
- Stops roundstart fire alarm in garden
- Maybe some other minor stuff
> Updates Kilostation

- maplestation_modules/code/datums/pain/pain_causes/surgery_pain.dm
Oops, you get moodlets when you're dead. Not intended.
> Surgery pain fix

- _maps/map_files/KiloStation/KiloStation.dmm
Desk shutters were only half operational
> Fixes a thing on Kilo med

- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/_multiline_text.tsx
Teehee, 21 month younger me was a fool
> Fixes multiline crashing servers

- maplestation_modules/code/modules/client/preferences/species/lizard.dm
- maplestation_modules/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
> Makes that one preference work correctly

- tools/requirements.txt
[tgstation/#76932](https://github.com/tgstation/tgstation/pull/76932)
> Fixes Linters

- _maps/map_files/KiloStation/KiloStation.dmm
- Removes 7 carpspawn, spaces them out a bit better(?)
- Fixes virology window
- Fixes bar sign
> Kilo fixes and fish nerfening

- maplestation.dme
- maplestation_modules/code/modules/reagents/machines.dm
I wouldn't be surprised if trying to use a |= on a null var breaks it but since it's originally a list in the first place I think I'll just go with it
I doubt we're gonna get tea leaves for green tea so I figured making it an upgrade would be good
> adds green tea as an upgrade reagent to soda machine

- _maps/limastation.json
- _maps/map_files/LimaStation/LimaStation.dmm
`space/basic` is not supposed to be instantiated, this should've been left blank as it defaults to space anyways.
> Fixes lima baseturfs

- code/game/objects/items/defib.dm
Idea came to me in the last round. The idea behind this is that if someone's in turbo shock, it helps expedite getting them back into the round in a stable state. 
Is it realistic? I dunno, but it's worth a try.
> Being defibbed abates shock and heals some pain 

- maplestation_modules/code/datums/pain/pain_implements.dm
- maplestation_modules/code/modules/cargo/packs.dm
- maplestation_modules/code/modules/reagents/chemistry/reagents/rim_reagents.dm
Fixes #337 
Modular code my beloved, byond my beloved.
> Fixes some bad glass typepaths

- code/__HELPERS/text.dm
- code/datums/brain_damage/mild.dm
- Dumbness trauma no longer does random speech, I think it's cringe
- Fix `unintelligize`ing speech getting rid of punctuation
> Some brain trauma tweaks

- code/modules/mob/living/carbon/human/species.dm
- maplestation_modules/code/modules/mob/living/carbon/human/heart_rework/cpr.dm
- Lets people CPR on people who don't actually need it (are just suffocating). 
- Compressions help a little with oxyloss to accommodate.
> CPR tweaks

- _maps/map_files/LimaStation/LimaStation.dmm
I thought I pr'd this a month ago
> Fix Lima's satellite's relay's depowering

- maplestation_modules/code/datums/mood_events/reagent_mood_events.dm
- maplestation_modules/code/game/objects/items/devices/radio/headset.dm
- maplestation_modules/story_content/armored_corps/code/mecha_weapons/laser_override.dm
- maplestation_modules/story_content/armored_corps/code/mecha_weapons/ppc_override.dm
> Removes typos from various maple specific things

- maplestation_modules/code/modules/mob/living/carbon/human/species_types/silverscale.dm
> Silverscale statue destruction fix

- code/game/say.dm
- code/modules/mob/living/living_say.dm
- code/modules/mob/living/silicon/ai/ai.dm
> Language arg fix

- code/datums/components/food/germ_sensitive.dm
- code/game/objects/items/food/packaged.dm
- code/modules/mob/living/basic/vermin/mouse.dm
- code/modules/reagents/reagent_containers/pill.dm
- Time for food to get dirty 5 seconds -> 1 minute. 
- Ration packs don't germ or decompose.
- ~~Rats don't germ, don't think about it. ~~ Nevermind I'm gonna revisit this later. 
- Pills don't germ.
> Adjusts Germs

- code/modules/tgui/states/greyscale_menu.dm
- maplestation_modules/code/modules/loadouts/loadout_items/loadout_datum_suits.dm
- Fixes greyscale menu being inoperable
- Adds Greyscale Suit Jacket on request
> Loadout fixes (The branch name is deceiving)

- code/game/say.dm
- code/modules/mob/living/living_say.dm
- code/modules/reagents/chemistry/reagents/impure_reagents/impure_medicine_reagents.dm
- strings/tips.txt
https://github.com/tgstation/tgstation/pull/81170
Also fixes whispering. 
Also fixes Tinacusiate.
> Runechat display fix for text effects

- code/controllers/subsystem/events.dm
Lower end from 2.5 minutes -> 5 minutes
Upper end from 7 minutes -> 15 minutes
> Tweaks event frequency

- code/modules/art/statues.dm
Ports Statue light fix from https://github.com/tgstation/tgstation/pull/81398
> Fixes Statues emitting solid lights (#81398)

- tgui/packages/tgui-panel/chat/constants.ts
> Fix LOOC tab being nonexistant

- maplestation_modules/code/modules/client/preferences/species/synth.dm
- maplestation_modules/code/modules/mob/living/carbon/human/species_types/synth/synth.dm
Last minute change going wrong, who would've thought it?
> Minor synth fix

- code/modules/mod/mod_clothes.dm
These should both be using the filter
> Fixes digi MODsuits

- maplestation.dme
- maplestation_modules/code/modules/cargo/goodies.dm
By request.
https://youtu.be/0UnwxdXT5GE
> You can now purchase peepy from cargo goodies section

- .vscode/settings.json
New contributors: I keep pushing to Master accidentally it sucks
Seasoned contributors: Just don't push to master lol, Just make sure you checked out a new branch lol
Maintainers: I keep pushing to Master accidentally it sucks
> Protect master

- maplestation.dme
- maplestation_modules/code/modules/mod/modules/modules_general.dm
- maplestation_modules/code/modules/research/designs/mechfabricator_designs.dm
- maplestation_modules/code/modules/research/techweb/all_nodes.dm
turns out i forgot to add it into techwebs and printable modules
whoops.
This also makes the complexity 1 instead of 3, as per other changes and reductions in the complexity of other modules.
> Makes the helmet desync module printable.

- maplestation_modules/code/modules/magic/story_spells/airhike.dm
Adds a 6 second cooldown similar to jump boots.
> Adds a cooldown to Airhike

- tgui/packages/tgui/components/Input.tsx
- tgui/packages/tgui/components/VirtualList.tsx
taken from https://github.com/tgstation/tgstation/pull/81968, will make searching not terrible
> crucial tgui fix taken from tg

- code/datums/datum.dm
- code/modules/clothing/glasses/_glasses.dm
- code/modules/clothing/head/wig.dm
- code/modules/mob/living/carbon/carbon_update_icons.dm
- code/modules/mob/living/carbon/human/_species.dm
- code/modules/mob/living/carbon/human/human_update_icons.dm
- maplestation_modules/code/modules/client/preferences/height.dm
Doing this in tandem with a TG pr because I realized my character was horribly ugly looking
> Height overlay fixes

- code/datums/components/udder.dm
- maplestation.dme
- maplestation_modules/code/modules/mob/basic/farm_animals/goat/goat_subtypes.dm
You can now milk Pete again. That's it. Pete just didn't have his top surgery done in the maple timeline.
Now comes with a free bug fix to the wonky text formatting.
> Pete is now a beautiful transmasc goat again

- maplestation_modules/code/modules/jobs/job_types/noble_ambassador.dm
- Code compiled and ran on local.
- Everything else is N/A.
> Changes Noble Ambassador budget and bounty to Service

- code/__DEFINES/mobs.dm
- code/modules/clothing/neck/_neck.dm
- code/modules/clothing/under/_under.dm
- code/modules/clothing/under/accessories/_accessories.dm
I'm impatient and I want this now
> Cherrypicks my neckties PR from upstream

- maplestation_modules/code/game/objects/structures/surgery_table.dm
yeah thats it
just a bug fix move along citizen
> null checks surgery tables, they can be deconned now

- code/modules/client/preferences.dm
- tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
Ports https://github.com/Skyrat-SS13/Skyrat-tg/commit/fe91d6981a67ad7ccb5a50d62af8472defc2567e for the dropdown.
nuff said, I want more characters dammit and even 8 when i was member was limiting.
> Increases character slots from 6 to 15, member slots to 20, makes Character Selection a dropdown.

- maplestation_modules/story_content/volkan_equipment/code/volkanpets.dm
In theory, Volkan's robotic pet should be able to survive breaches after this PR!
> Volkan's shoulder pet can now survive breaches.

- maplestation_modules/story_content/volkan_equipment/code/volkanpets.dm
The last PR of mine accidentally did not actually fix the issue of Volkan's pet from dying in space.
This one was actually tested and now it won't die in space.
Let's just say that IC Volkan has fixed its in-space cooling capabilities.
> Actually fixes Volkan's shoulder companions space issue!! For real this time.

- code/_onclick/hud/human.dm
- code/modules/mob/living/carbon/human/inventory.dm
- code/modules/mob/living/carbon/inventory.dm
- code/modules/surgery/bodyparts/robot_bodyparts.dm
> More slots now darken if you can't equip to it

- code/modules/mob/living/living.dm
- code/modules/surgery/organs/internal/eyes/_eyes.dm
If you fall asleep/unconscious (or die), your eyes will close. 
This does not apply to robotic eyes (they will always be wide open) or eyes that don't have color (like moth eyes - it would be better suited to give those unique shut sprites)
> Get some shut-eye

- code/modules/vending/medical.dm
Forgot to throw these in there when porting
> Adds missing crutches to med vendor

- maplestation_modules/code/modules/mob/living/carbon/human/species_types/abductor.dm
> Abducter Lore

- _maps/RandomZLevels/TheBeach.dmm
- code/datums/components/riding/riding_vehicle.dm
- code/modules/vehicles/lavaboat.dm
Adds a station telecomms relay and some towel racks.
And then also adds a few islands and such to explore. Spoilers!
> Beach expansion [MDB Ignore]

- code/modules/clothing/gloves/insulated.dm
- code/modules/clothing/masks/hailer.dm
I like these things having these things, I think it's more fun
> -Chunky finger insuls, +Pepper proof sec hailers

- code/game/objects/structures/window.dm
- maplestation_modules/code/game/machinery/pager.dm
- maplestation_modules/code/modules/reagents/chemistry/reagents/rim_reagents.dm
Spellchecks some stuff
Also renames windows, because I don't like that `full tile windows` are named `full tile windows` and not just `windows`
> Spell checks and renames

- code/datums/status_effects/debuffs/grabbed.dm
Inspired by Goon's implementation
`*flip`ping when you have someone neck grabbed (but not pinned down) will perform a suplex, causing damage, a minor stun, and a knockdown.
In return you sustain minor stamina damage and get floored yourself for a short time.
> Adds suplex

- code/game/objects/items/handcuffs.dm
- maplestation_modules/code/modules/mob/dead/new_player/sprite_accessories.dm
1. Updates the clown self-handcuff interaction to be less out of line with how handcuffs work
2. Fixes a bug with spines and the larger lizard tail
> Two random things

- code/game/machinery/slotmachine.dm
- tgui/packages/tgui/interfaces/SlotMachine.tsx
`https://github.com/tgstation/tgstation/pull/81700`
> Cherrypicks "converts the slot machine over to TGUI"

- maplestation_modules/code/modules/reagents/chemistry/reagents/rim_reagents.dm
Simple fix: Go-Juice doesn't have one of its requirements set properly, so it cannot react. 
This sets it properly, of course
> Fixes Go-Juice's Reaction.

- code/modules/surgery/organs/internal/tongue/_tongue.dm
> Fix Silverscale statue on Multi z maps

- code/__DEFINES/preferences.dm
- code/datums/components/trader/trader.dm
- code/game/objects/items/cosmetics.dm
- code/modules/clothing/head/hat.dm
- code/modules/clothing/masks/costume.dm
- code/modules/clothing/suits/moth.dm
- code/modules/clothing/under/shorts.dm
- code/modules/clothing/under/skirt_dress.dm
- maplestation_modules/code/modules/client/preferences/loadout_preference.dm
- maplestation_modules/code/modules/clothing/suits/armor.dm
- maplestation_modules/code/modules/clothing/under/loadout_under.dm
- maplestation_modules/code/modules/loadouts/loadout_items/_loadout_categories.dm
- maplestation_modules/code/modules/loadouts/loadout_items/_loadout_datum.dm
- maplestation_modules/code/modules/loadouts/loadout_items/loadout_datum_heads.dm
- maplestation_modules/code/modules/loadouts/loadout_items/loadout_datum_pocket.dm
- maplestation_modules/code/modules/loadouts/loadout_items/loadout_datum_under.dm
- maplestation_modules/code/modules/loadouts/loadout_ui/loadout_outfit_helpers.dm
- tgui/packages/tgui/interfaces/PreferencesMenu/loadout/ItemDisplay.tsx
- tgui/packages/tgui/interfaces/PreferencesMenu/loadout/base.ts
Adds support for custom loadout items
Gives some loadout items which were errors a preview icon
Adds support for custom lipstick colors (and now it applies it for you)
> Support for holiday loadout items (and also custom lipstick colors I guess) 

- code/datums/emotes.dm
- code/modules/mob/living/carbon/emote.dm
- code/modules/mob/living/emote.dm
Inspired by upstream (which factors in TTS pitch), emote sounds produced but "your mouth" will be affected by pitch or frequency of your character. 
So screams of a high pitch character are high pitched, etc.
> Emotes are affeceted by voice pitch / frequency

- maplestation_modules/code/modules/wiremod/shells.dm
What the tin says
Honestly here mostly for a more personalized translator design I've stumbled across that I liked a lot lmao
> Headset circuit shells output their wearer

- code/modules/mob/living/carbon/carbon.dm
> Buckle fix

- tgui/packages/tgui-bench/package.json
- tgui/packages/tgui-panel/package.json
- tgui/packages/tgui-say/package.json
- tgui/packages/tgui/package.json
- tgui/yarn.lock
Updates TGUI-Core to fix some things broken by the last upstream version bump
> Tgui core version bump

- code/game/objects/structures/signs/_signs.dm
- code/game/objects/structures/signs/signs_departments.dm
Surprised they didn't fail the tests
> Fix stealth runtimes

- code/datums/components/infective.dm
- code/game/objects/effects/decals/cleanable.dm
- code/game/objects/effects/decals/cleanable/humans.dm
- code/modules/mob/living/blood.dm
- code/modules/mob/living/carbon/alien/alien.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/death.dm
- code/modules/mob/living/living.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
- maplestation_modules/code/modules/mob/living/blood.dm
Maybe inspired by recent events
> If you are bleeding extensively, you will leave a trail when standing (walking), rather than only when floored (crawling)

- code/game/atom/atom_examine.dm
- code/game/machinery/camera/camera.dm
- code/modules/antagonists/nukeop/nukeop.dm
- code/modules/shuttle/computer.dm
- maplestation_modules/code/__DEFINES/paperwork_defines.dm
- maplestation_modules/code/modules/antagonists/_common/antag_datum.dm
- tgui/packages/tgui-setup/helpers.js
- tgui/packages/tgui/interfaces/NtosMain.tsx
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
- tgui/packages/tgui/interfaces/_OperatingComputer.tsx
- tgui/packages/tgui/styles/themes/ntos_terminal.scss
Melbert asked me to do this since he wanted the 516 PR in before the next round and is too busy for cleanup, I oblige.
> post-516 Linter fix and such

- maplestation.dme
- maplestation_modules/code/modules/magic/story_spells/freeze_person.dm
makes it so you need a do_after to freeze someone cuz having you be able to stop someone instantly is kind of cringe as fuck
also added some description to tell that u can actually resist out of the cube as well
> Cryokinesis Coldfix

- code/__HELPERS/_lists.dm
- code/controllers/configuration/entries/game_options.dm
- code/controllers/subsystem/events.dm
- code/modules/events/_event.dm
- config/events.json
- config/game_options.txt
Lets you individually configure events, finally
> Ports events configs

- maplestation_modules/code/datums/pain/pain.dm
- maplestation_modules/code/datums/pain/pain_implements.dm
Autotomy reduces the amount of pain received from losing limbs - this applies to all limb loss instead of just from manually dropping limbs
Fixes copypasta with painkiller medipens
> Autotomy patch / Medipen fix

- code/modules/cargo/orderconsole.dm
- code/modules/events/shuttle_loan/shuttle_loan_event.dm
- maplestation_modules/code/modules/events/resource_drift.dm
- maplestation_modules/code/modules/events/resource_pods.dm
- maplestation_modules/code/modules/events/solar_flare.dm
Fix shuttle loan, fix loaning from request cargo consoles, fix our events not having categories.
> Shuttle loan and event fixes

- maplestation_modules/code/modules/mining/order_consumables.dm
> Survival Pen Fix

- code/modules/atmospherics/environmental/LINDA_fire.dm
Ports the two updates to hotspots that stop infinite fire death
> Hotspot fixes

- maplestation_modules/story_content/wollys_items/code/wollysitems.dm
When pring the content for elijah i forgot to finish the description & add internals flag before merge, this does that.
> Finishes up elijah's mask

- code/modules/mob/living/blood.dm
> Hivebots bleed oil

- code/datums/mergers/_merger.dm
- code/game/objects/effects/wanted_poster.dm
- code/modules/modular_computers/file_system/program_circuit.dm
- code/modules/power/singularity/field_generator.dm
Fixes issues from lang server updates
> Lang server fixes

- code/modules/projectiles/ammunition/_firing.dm
- code/modules/projectiles/ammunition/energy/laser.dm
- code/modules/projectiles/ammunition/energy/stun.dm
- code/modules/projectiles/guns/energy/beam_rifle.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/projectile.dm
- code/modules/projectiles/projectile/beams.dm
Hitscan lasers are awesome conceptually but they were really really oppressive because you would die in 4 hits. 
...But with our health system, a laser can't kill you in 4 hits. So they might work? Maybe?
(This also makes disablers less of a water gun, something I've noticed since stamina was nuked)
> (Maybe just for test) Retrvn to hitscan lasers/disablers

- code/modules/events/wisdomcow.dm
1. It's a little goofy when the round's getting serious and NT starts yapping about cows
2. Stealth cows might be funnier?
> Hides the wise cow announcement

- code/game/machinery/computer/orders/order_items/cook/order_milk_eggs.dm
- code/game/machinery/computer/orders/order_items/cook/order_reagents.dm
- code/game/machinery/computer/orders/order_items/cook/order_veggies.dm
Updates it so I don't lose my mind gaslighting myself about an ingredient I KNOW I can order
Adds:
- Moonfish
- Cleaned Armorfish
- Honey
- Mayo
- And a bunch of various fruits and veggies
> Adds a bunch of missing ingredients to the produce console

- code/game/objects/items/devices/flashlight.dm
- maplestation_modules/code/datums/pain/pain_status_effects/anesthetic.dm
- maplestation_modules/code/game/objects/structures/surgery_table.dm
- maplestation_modules/code/modules/client/preferences/height.dm
Damn that's maybe a year long mistake
Also fix surgery, also add a tell to grog
> Fix wrong height being available all this time

- code/game/objects/structures/crates_lockers/closets/secure/security.dm
> Adds non-sunglasses sechud varients to sec lockers

- code/modules/mob/living/basic/bots/_bots.dm
- code/modules/mob/mob.dm
No more bots smashing their heads on airlocks
> Fix bot access, fix examine more

- code/modules/mob/living/basic/bots/cleanbot/cleanbot.dm
For the people who can't reach an ash tray
> Cleanbots clean cigarette butts
